EtsiiMarktProject/EtsiiMarkt/urls.py
from django.contrib import admin
from django.urls import path, include
#from clientes.views import RegistroClienteView
from clientes.views import IniciarSesionView, editar_direccion_envio, logout_personalizado, modificar_datos_usuario, perfil, register
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from core.views import index, nosotros, devoluciones
from productos.views import catalogo, catalogo2
from pedidos.views import actualizar, eliminar, formulario_envio, procesar_pedido, pedidos_usuario, error
from pedidos.views import agregar_reclamacion, editar_reclamacion, reclamaciones_cliente, eliminar_reclamacion
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('catalogo/', catalogo, name='catalogo'),
    path('busqueda/', catalogo2, name='catalogo2'),
    path('login/', IniciarSesionView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registro/', register, name='registro_usuario'),
    path('perfil/', perfil, name='perfil_usuario'),
    path('modificar_perfil/', modificar_datos_usuario, name='modificar_perfil'),
    path('actualizar/<int:producto_id>/', actualizar, name='actualizar'),
    path('eliminar/<int:producto_id>/', eliminar, name='eliminar'),
    path('formulario_envio/<int:pedido_id>/', formulario_envio, name='formulario_envio'),
    path('pedido_realizado/', procesar_pedido, name='procesar_pedido'),
    path('seguimiento/', pedidos_usuario, name='seguimiento'),
    path('error/<str:error>/', error, name='error'),
    path('pedido/<int:pedido_id>/agregar-reclamacion/', agregar_reclamacion, name='agregar_reclamacion'),
    path('pedido/<int:reclamacion_id>/editar_reclamacion/', editar_reclamacion, name='editar_reclamacion'),
    path('pedido/<int:reclamacion_id>/eliminar_reclamacion/', eliminar_reclamacion, name='eliminar_reclamacion'),
    path('pedido/reclamaciones_cliente/', reclamaciones_cliente, name='reclamaciones_cliente'),
    path('nosotros', nosotros, name='nosotros'),
    path('devoluciones', devoluciones, name='devoluciones'),
    path('logout_personalizado', logout_personalizado, name='logout_personalizado'),
    path('clientes/direccion_envio/', editar_direccion_envio, name='editar_direccion_envio'),
]
    

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

EtsiiMarktProject/clientes/urls.py
from django.contrib import admin
from django.urls import include, path

from .models import Producto
from .views import catalogo, detalle, editar_direccion_envio, index
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [    
        path('home', index, name='index'),
        path('editar_direccion_envio', editar_direccion_envio, name='editar_direccion_envio'),
]

EtsiiMarktProject/pedidos/models.py
from enum import Enum
from django.db import models

from productos.models import Producto

from django.contrib.auth.models import User

# Create your models here.
class EstadoProducto(Enum):
    EN_PREPARACION = 'En preparación'
    ENVIADO = 'Enviado'
    ENTREGADO = 'Entregado'

    
class Pedido(models.Model):
    user=models.ForeignKey(User,on_delete=models.SET_NULL, null=True, blank=True)
    destinatario=models.CharField(max_length=1000, null=True, blank=True)
    fecha_pedido=models.DateTimeField(auto_now_add=True)
    completado=models.BooleanField(default=False)
    id_transaccion=models.CharField(max_length=100, null=True)
    estado = models.CharField(max_length=20, choices=[(estado.value, estado.value) for estado in EstadoProducto], null=True, blank=True)


    @property
    def get_total_carrito(self):
        productopedidos=self.productopedido_set.all()
        total=sum([p.get_total for p in productopedidos])
        if total<200 and len(productopedidos)>0:
            total=total+15
        return total
    
    @property
    def get_productos_carrito(self):
        productopedidos=self.productopedido_set.all()
        total=sum([p.cantidad for p in productopedidos])
        return total
    
    def get_estado(self):
        if str(EstadoProducto.EN_PREPARACION)==self.estado:
            return 'En preparación'
        if str(EstadoProducto.ENTREGADO)==self.estado:
            return 'Entregado'
        if str(EstadoProducto.ENVIADO)==self.estado:
            return 'Enviado'
    
    def get_lista_de_productos_carrito(self):
        productos = [producto_pedido for producto_pedido in self.productopedido_set.all()]
        return productos

    def __str__(self):
        return "Pedido con con id " + str(self.id)

class ProductoPedido(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.SET_NULL, null=True)
    pedido= models.ForeignKey(Pedido, on_delete=models.SET_NULL, null=True)
    montar_domicilio= models.BooleanField(default=False)
    cantidad = models.IntegerField(default=0, null=True, blank=True)

    @property
    def get_total(self):
        if self.montar_domicilio==True:
            return self.producto.precio*self.cantidad+self.cantidad*15
        else:
            return self.producto.precio*self.cantidad

class DireccionEnvio(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    pedido = models.ForeignKey(Pedido, on_delete=models.SET_NULL, null=True)
    direccion = models.CharField(max_length=200, null=False)
    ciudad = models.CharField(max_length=200, null=False)
    codigo_postal= models.CharField(max_length=200, null=False)
    
    def __str__(self):
        return self.direccion + ", " + self.ciudad

class Reclamacion(models.Model):
    ESTADO_CHOICES = [
        ('por_resolver', 'Por Resolver'),
        ('en_proceso', 'En Proceso'),
        ('solucionado', 'Solucionado'),
    ]

    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, null=False)
    cuerpo = models.CharField(max_length=500)
    resolucion = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='por_resolver', verbose_name="Estado de la Reclamación")

    class Meta:
        ordering = ['pedido']
        verbose_name_plural = 'Reclamaciones'

    def __str__(self):
        return f"Reclamación de {self.pedido.user.username} en el pedido {self.pedido.id}"

EtsiiMarktProject/templates/envios/agregar_reclamacion.html
{% extends "base.html" %}

{% block title %}Agregar Reclamación{% endblock %}

{% block content %}
  <h2>Agregar Reclamación</h2>
  <div>
    
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}

      <button type="submit" class="btn btn-secondary">Enviar reclamación</button>
    </form>

  </div>
{% endblock %}

EtsiiMarktProject/templates/envios/editar_reclamacion.html
{% extends "base.html" %}

{% block title %}Editar Reclamación{% endblock %}

{% block content %}
  <h2>Editar Reclamación</h2>
  
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><h6>Si se cambia la reclamación se procesará de nuevo, por lo que volverá al estado de Por Resolver.</h6></p>
    <button type="submit" class="btn btn-secondary">Guardar cambios</button>
  </form>
{% endblock %}

EtsiiMarktProject/templates/envios/eliminar_reclamacion.html
{% extends "base.html" %}

{% block title %}Confirmar Eliminación{% endblock %}

{% block content %}
  <h2>Confirmar Eliminación</h2>
  <p>¿Estás seguro de que deseas eliminar la reclamación?</p>
  
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'reclamaciones_cliente' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock %}

EtsiiMarktProject/templates/envios/formulario_envio.html
{% extends 'base.html' %}

{% block title %}Dirección de envío del pedido{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario de Envío</title>
</head>
<body>
    <h2>Formulario de Envío</h2>
    <div class="formulario-envio border p-3">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <form method="post" action="{% url 'procesar_pedido' %}">
        {% csrf_token %}

        Seleccione el método de pago:
        <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="formaPago" value = "{{formaPago}}">
            {% if formaPago == 'pasarela' %}
            <option value="contrarrempolso">Contrareembolso</option>
            <option value="pasarela" selected>Pago online con tarjeta de crédito</option>
            {% else %}
            <option value="contrarrempolso" selected>Contrareembolso</option>
            <option value="pasarela">Pago online con tarjeta de crédito</option>
            {% endif %}
          </select>
        <br>
        {% if user.is_authenticated %}
        <input type="hidden" name="destinatario" required value = "{{destinatario}}"></p>
        <input type="hidden" name="email" required value = "{{email}}"></p>
        <p><label for="direccion">Dirección de Envío:</label>
        <input type="text" name="direccion" required value = "{{direccion}}"></p>
        <p><label for="ciudad">Ciudad:</label>
        <input type="text" name="ciudad" required value = "{{ciudad}}"></p>
        <p><label for="postal">Código postal:</label>
        <input type="number" name="postal" required value = "{{postal}}"></p>
        {% else %}
        <p><label for="destinatario">Destinatario:</label>
        <input type="text" name="destinatario" required value = "{{destinatario}}"></p>
        <p><label for="direccion">Dirección de Envío:</label>
            <input type="text" name="direccion" required value = "{{direccion}}"></p>

            <p><label for="ciudad">Ciudad:</label>
            <input type="text" name="ciudad" required value = "{{ciudad}}"></p>

            <p><label for="postal">Código postal:</label>
            <input type="number" name="postal" required value = "{{postal}}"></p>
        {% endif %}

        {% if user.is_authenticated %}
        <input type="hidden" name="email" required value = "{{email}}"></p>
        {% else %}
        <p><label for="email">Email:</label>
            <input type="email" name="email" required value = "{{email}}"></p>
        {% endif %}

        <p><input name="pedido_id" type="hidden" value="{{pedido_id}}" /></p>



        <button class="btn btn-secondary" type="submit">Continuar</button>
    </form>
</div>

</body>

{% endblock %}

EtsiiMarktProject/templates/envios/reclamaciones_cliente.html
{% extends "base.html" %}

{% block title %}Mis Reclamaciones{% endblock %}

{% block content %}
  <h2>Mis Reclamaciones</h2>
  
  <div class="mb-4">
    <a class="btn btn-secondary" href="{% url 'seguimiento' %}">Agregar reclamación</a>
  </div>

  {% if reclamaciones %}
    <table class="table">
      <tr>
        <th>Fecha</th>
        <th>Mensaje</th>
        <th>Estado</th>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      {% for reclamacion in reclamaciones %}
        <div class="col-3">
          <tr>
            <td>{{ reclamacion.pedido.fecha_pedido|date:"d/m/Y" }}</td>
             <td>{{ reclamacion.cuerpo }}</td>
              <td>{{ reclamacion.get_resolucion_display }}</td>
         
          <td>
            <a href="{% url 'editar_reclamacion' reclamacion.id %}" class="btn btn-secondary">Editar</a></td>
           <td><a href="{% url 'eliminar_reclamacion' reclamacion.id %}" class="btn btn-danger">Eliminar</a></td>
          </tr>
       
      {% endfor %}
        </table>
  {% else %}
    <p class="text-center">No tienes reclamaciones.</p>
  {% endif %}
{% endblock %}

EtsiiMarktProject/templates/envios/resultado_envio.html
{% extends "base.html" %}

{% block title %}Catálogo de Productos{% endblock %}

{% block content %}

<h2>PEDIDOS REALIZADOS</h2>

<div class="resultado-envio">

    {% include 'message.html' %}
    
</div>

{% endblock %}

EtsiiMarktProject/templates/envios/seguimiento.html
{% extends "base.html" %}

{% block title %}Catálogo de Productos{% endblock %}

{% block content %}

<h2>PEDIDOS REALIZADOS</h2>

<div class="pedidos-realizados row">


{% include 'message.html' %}   

{% if not user.is_authenticated %}
<div class="row border p-3 ">
<form role="search" method="get" action="{% url 'seguimiento' %}" >
  <div class="col-12 mb-3">
    <label for="search">Introduce tu número de pedido:</label>
  </div>
  <div class="col-12">
    <input class="form-control mb-3" type="text" name="idPedido" id="search">
    <button class="btn btn-secondary" type="submit">Buscar</button>
  </div>
</form>
</div>
{% endif %}
  {% for pedido in pedidos %}
  <div class="border p-3 mb-5">
  <div class="border row p-3 fw-bold bg-body-secondary mb-3">
    <div class="col-3">Fecha: {{ pedido.fecha_pedido|date:"d/m/Y" }}</div>
    <div class="col-3">Estado: {{ pedido.get_estado }}</div>
    <div class="col-3">Total: {{ pedido.get_total_carrito }} €</div>
    <div class="col-3">
      {% if user.is_authenticated %}
        <a class="btn btn-secondary" href="{% url 'agregar_reclamacion' pedido.id %}">Crear reclamación</a>
      {% endif %}
    </div>
  </div> 
  <div class="row">
  <table class="table col-12">    
    <tr>
      <th>Producto</th>
      <th>Unidades</th>
      <th>Precio</th>
    </tr>
            {% for item in pedido.get_lista_de_productos_carrito %}
            <tr>
                <td>{{ item.producto.nombre }}</td>
                <td>{{ item.cantidad }}</td>
                <td>{{ item.get_total }} €</td>
            </tr>
            {% endfor %}
     
      </table>        
         
        </div>
      </div>
  {% endfor %}
      
</div>


{% endblock %}